name: 'Run Linters'

on:
  pull_request:
    paths:
      - '.github/workflows/*.yml'
      - '.github/workflows/*.yaml'

permissions:
  contents: read

jobs:
  linters:
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
        with:
          egress-policy: audit

      - name: Checkout Repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install yq
        uses: frenck/action-setup-yq@c4b5be8b4a215c536a41d436757d9feb92836d4f # v1.0.2
      
      - name: Install shellcheck
        env:
          SHELLCHECK_PREFIX: ${{ runner.temp }}
        run: |
          CURL='curl -fsS --retry 5 --retry-max-time 30'
          URL=$(\
            $CURL -L https://api.github.com/repos/koalaman/shellcheck/releases/latest \
            | jq -r '.assets[] | select(.name? | match("shellcheck_*.*.*.linux.x86_64.tar.xz$")) | .browser_download_url'\
          )
          VERSION=$(\
            $CURL -L https://api.github.com/repos/koalaman/shellcheck/releases/latest \
            | jq -r '.tag_name'\
          )
          $CURL -L "${URL}" | xzcat | tar -C $SHELLCHECK_PREFIX -xvf - shellcheck-$VERSION/shellcheck
          $SHELLCHECK_PREFIX/shellcheck-$VERSION/shellcheck --version

          echo "$SHELLCHECK_PREFIX/shellcheck-$VERSION/shellcheck" >> "$GITHUB_PATH"

      - name: Run shellcheck
        run: bin/shellcheck.sh

